version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: fluxpay-postgres
    restart: always
    environment:
      POSTGRES_USER: fluxpay
      POSTGRES_PASSWORD: fluxpay123
      POSTGRES_DB: fluxpay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
